- README.md
I've written a short article on how to get Vite with TypeScript + Preact up and running. Maybe that's a worthy addition to your list :-)
> add Vite + Preact + TypeScript article

- README.md
> add Tailwind Pre-Processor

- README.md
> Added vite-plugin-rust

- README.md
> Add npmview to Apps/Websites

- README.md
> Add kirby-vue3-starterkit to templates

- README.md
> feat: added vite-plugin-mock

- README.md
add a simple mock plugin.
> If you cannot detect vue with `vue-devtools` due to work at non public pages (e.g. for enterprise website), you can send Pull Request with screenshot that detected it.
> add(testing): vite-plugin-mockit

- README.md
> add(open-source): troisjs

- README.md
> add(templates): vite-ts-tailwind-starter

- README.md
> feat: add vue vben admin

- README.md
A markdown & vue3 preview plugin for vite.
> feat: add vite-plugin-vuedoc

- README.md
> feat: add electron-vue-next

- README.md
Made the plugins for other frameworks part less misleading
> Made the plugins for other frameworks part less misleading

- README.md
> feat: add vite-plugin-html

- README.md
> fix: vite-plugin-vite to  vite-plugin-pwa

- README.md
> feat: add vite-components-playground

- README.md
added a new webapp with vite and tailwind hosted on netlify.
- [] Title as described
> feat: add TypGame

- README.md
> feat: add vite-electron-builder

- README.md
> Add vite-ssr and vitedge

- README.md
> feat: add vite-plugin-md

- README.md
Something I've been using and maybe comes useful to someone else.
> Add vite-test

- README.md
> feat: add vite-plugin-toml

- README.md
> feat: add vite-plugin-faker

- README.md
https://github.com/web2033/vite-vue3-tailwind-starter
> Add Starter Template

- README.md
> feat: add vite-plugin-i18n-resources

- README.md
> chore: update vite-plugin-vuedoc support vite 2.0

- README.md
> Add vite-plugin-fonts

- README.md
> Add vite-eslint

- README.md
> feat: Adding Solid library + plugin

- README.md
Using alphabetical order for official rollup plugins.
> chore: compatible @rollup/plugin-graphql, @rollup/plugin-yaml

- README.md
> docs: update vite-plugin-vue-i18n

- README.md
> add vite-ts-tailwind-starter

- README.md
Add [vite-plugin-svgr](https://github.com/pd4d10/vite-plugin-svgr)
> feat: add vite-plugin-svgr

- README.md
> add vite-plugin-react-pages

- README.md
> add vite-plugin-multi-device

- README.md
> Add vite-electron-builder template

- README.md
> Add Vite Rails and create a section of backend integrations

- README.md
> feat: add vite-plugin-rsw

- README.md
vite@2 compatible
https://github.com/aleclarson/vite-tsconfig-paths
> feat: add vite-tsconfig-paths

- README.md
> feat: add vite-plugin-pages

- README.md
> Add vite-reactts-electron-starter

- README.md
Sorry forgot to add it to the toc.
> Add missing React link to toc

- README.md
> feat: add vite-plugin-compress

- README.md
> feat: add vue-vben-admin template

- README.md
> feat: add vite-plugin-mock

- README.md
> feat: add vite-plugin-style-import

- README.md
> feat: add vite-plugin-mocker

- README.md
> Add vite-ssr and vitedge (now support Vite 2)

- README.md
> feat: add vite-plugin-imagemin

- README.md
- [ x The documentation (README) contains a description of the project, illustration of the project with a demo or screenshots and a CONTRIBUTING section
> Add vite-imagetools to loader list

- README.md
Add an open source web app I made using Vite.
- [x ] Make sure you put things in the right category.
- [ x The description of your item should be a sentence with less than 24 words.
> add: aitrack.work

- README.md
> Add MacOS Web to the list

- README.md
Vite plugin with mocha and puppeteer
Headless test your Vue, React and Lit-Element component
> add vite-plugin-test

- README.legacy.md
- README.md
> doc: add vue2 starter template

- README.md
> docs: add vite-plugin-importer

- README.md
A banner plugin for Vite. It can adds a banner to the top of each generated chunk.
> Add vite-plugin-banner.

- README.md
_It's currently 47_.
_Released on `27. Feb. 2021`_.
_No website or app_
> feat: add vite-plugin-ts-nameof

- README.md
As per title: React, Typescript, Chakra, Cypress. An included Demo to know where to start with a small written Cypress test to get you started.
> Add vite-reactts-chakra-starter

- README.md
- it is important and helpful to beginners, how to migration from other tools like vue-cli/create-react-app and so on.
- maybe something like cra-to-vite.
> feat: add new category, migrations

- README.md
> feat: add vite-plugin-handlebars

- README.md
- [] The repo should be at least 30 days old.
> feat: add vite-plugin-mpa

- README.md
> feat: add vite-aliases

- README.md
> feat: add vite-plugin-cesium

- README.md
> feat: add vite-plugin-svg-icons and vite-plugin-compression

- README.md
> feat: added [electron-vite-react] and [vite-plugin-twstyled]

- README.md
> doc: Update links to Vite Ruby

- README.md
> Add vite-electron-esbuild-starter

- README.md
> doc: add vite-plugin-import

- README.md
> feat: add Vitamin

- README.md
> Add Svelte section and sttv starter template

- README.md
> Add vite-plugin-radar

- README.md
> feat: add d2-advance

- README.md
> add vite-react-tailwind-rtk

- README.md
Hi there, just throwing in my simple vite + vue2 starter project, please let me know if there's anything I need to change.
> Add vite-vue2-starter to Readme

- README.md
https://github.com/jiangfengming/svelte-vite-ssr
> Add svelte-vite-ssr template

- README.md
> docs: add vite-plugin-imp to README

- README.md
> Add vite-preset-react

- README.md
> docs: add vite-plugin-html-config plugin

- README.legacy.md
- README.md
> docs: add vue-pure-admin

- README.md
Add https://github.com/brillout/vite-plugin-ssr
> feat: add vite-plugin-ssr

- README.md
> feat: add vite-electron-ts

- README.md
> feat: add vite-plugin-vue-gql

- README.md
> Add vite-reactts-eslint-prettier

- README.md
add react typescript with ant design example
> add react typescript with ant design example

- README.md
> add vite-electron-typescript-template

- README.md
Added [view-launcher](https://github.com/view-launcher/view-launcher)
> Add "view-launcher"

- README.md
> docs: add Slidev

- README.md
> docs: add @vitjs/vit

- README.md
> feat: add vite-plugin-html-template

- README.md
Added testing-solutions mentioned or developed in the context of https://github.com/vitejs/vite/issues/2294#
> feat: add vite testing solutions

- .gitignore
- README.md
> docs: add wp2vite

- README.md
> docs: update vite-ssr description

- README.md
Hello , I have been added a new plugin named ```vite-plugin-md2vue``` in in Transformers category, this is repository's address: [vite-plugin-md2vue](https://github.com/WangXueZhi/vite-plugin-md2vue)
> add: vite-plugin-md2vue in Transformers 

- README.md
> Add vite-template-react

- README.md
> Add django-vite integration

- README.md
> feat: add vite-plugin-virtual-html

- README.md
> feat: add vite-plugin-mkcert

- README.md
> Add AEM Vite to integrations

- README.md
React, Recoil, React Query, React Hooks, Typescript, Axios
> Add react-vite-admin

- README.legacy.md
- README.md
vite-ts-quick, use vite 2.x + Vue 3.x + Vuex 4.x + Vue-router 4.x + Typescript. 
Contain Cookie + Storage + NetBase(Fetch).
> feat: new vue3 template [vite-ts-quick]

- README.md
> feat: add apps

- README.md
> Add fast-crud

- README.md
Signed-off-by: Andrew Welch <andrew@nystudio107.com>
Checked and verified
> Add Craft CMS integration plugin + article

- README.md
> Add admin-base-tmpl

- README.md
> feat: add vite-plugin-vconsole

- .gitignore
- README.md
> feat: vivu

- README.md
> docs: add electron-vite-quick-start

- README.md
> feat: add vite-plugin-cdn-import

- README.md
> Add jihchi/vitejs-template-react-rescript repo, React + ReScript

- README.md
> Add transformer vite-plugin-plain-text

- README.md
> Add Loader vite-plugin-virtual-plain-text

- README.md
> docs: add vite plugin spritesmith

- README.md
> feat: add vite-vue3-lowcode

- README.md
> docs: add vite-plugin-dts

- README.md
for https://github.com/vitejs/vite/issues/2467 and https://github.com/vitejs/vite/discussions/1707
> add vite-plugin-host

- README.md
> docs: add vite-plugin-externals

- README.md
> add vite-plugin-eruda

- README.md
> docs: add dashboard example app

- README.md
> Add vite-react-rtkq template

- README.md
> docs: add vite-plugin-async-catch

- README.md
> docs: add vue3-SSR-starter

- README.md
> add electron-vite-template

- README.md
> docs: add vite-plugin-virtual-html-template

- README.md
> docs(templates): add vue-vite-h5

- README.md
> docs: add vite-plugin-mock-server

- README.md
> docs(templates): add electron-vue-vite

- README.md
> Move vite-plugin-multi-device to framework agnostics

- README.md
> Add vite-plugin-linter

- README.md
> docs: add vite-plugin-checker

- README.md
Fix a typo related to the Table of Contents in the documentation.
> Fix phrasing of Table of Contents

- README.md
> add vite-plugin-require-context

- README.md
> feat: new react template [vite-react-quick]

- README.md
> docs: add vite-plugin-vue-docs

- README.md
> docs(templates): add vite-template-react-plus

- README.md
> docs: add vite-plugin-dynamic-publicpath

- README.md
> 📄 Add vite-boilerplate (full-stack template)

- README.md
> Update README.md : Add link of vitawind

- README.md
> fix: update vite-plugin-vue-i18n repo link

- README.md
> docs: add vitesome template

- README.md
> Add react with tailwindcss + tests

- README.md
> Add vite-plugin-restart and vite-plugin-full-reload to Helpers section

- README.md
> docs: Add vite-plugin-stimulus-hmr

- README.md
> docs: add plugin 'vite-plugin-tips'

- README.md
👋 hi there. Hopefully the [project homepage](https://tropical.js.org/) explains what it's about, but let me know if you need any more info. Thanks!
- It's more boilerplate than a visual template, but the docs site `tropical.js.org` is a live demo
> docs: add Tropical

- README.md
> add vite-plugin-commonjs

- README.md
The original link is broken (deprecated), update the link to correct one.
---
N/A
N/A
N/A
> docs: Fix a broken link

- README.md
> Move Django item into its own category

- README.md
> Add Vue 3 SSR templates

- README.md
> feat: add vue2/3 todo action template

- README.md
> Alphabetize section "Integration with Backends"

- README.md
The issue [4322](https://github.com/vitejs/vite/issues/4322) I created was closed, and I can not wait to see `@vitejs/plugin-react` being released.
> docs: add vite-plugin-react-refresh

- README.md
This PR adds my [Laravel integration](https://github.com/innocenzi/laravel-vite) to the list.
> add(integrations): Laravel Vite

- README.md
> feat: Added vite-reactts17-chakra-jest-husky to React templates

- README.md
> add(SSR frameworks): vitext

- README.md
> fix: heading level

- README.md
A vite plugin for the Monaco Editor.
> Add vite-plugin-monaco-editor

- README.md
- [ x ] Title as described.
- [ x ] Make sure you put things in the right category.
- [ x ] The description of your item should be a sentence with less than 24 words.
- [ x ] Omit unnecessary words already provided in the context (e.g. `for Vite`, `a Vite plugin`).
- [ x ] The website is available without errors and load in a reasonable amount of time.
- [ x ] The website must be Open Source and showing it's using Vite intensively.
- [ x ] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.
> Change macOS Web to macOS Svelte

- README.md
> added vite-plugin-relay

- README.md
> Add Vue2 typescript example

- README.md
> Add Rakkas to SSR frameworks

- README.md
> docs: add vite-plugin-vars-modifier

- README.md
> Add: Vue Component Template

- README.md
> Add: sections for Elm to templates and integrations

- README.md
> add: reat-ts-vite-template

- README.md
> add webpack-to-vite

- README.md
It's not really a template, it's more of an enhancement to create-vite
Up to you to decide about the final three items.
> Add create-vite-pwa

- README.md
> add: vite-reactts-tailwind-rtk-eslint

- README.md
add - https://github.com/baileyherbert/svelte-vite-starter
> new template  baileyherbert/svelte-vite-starter

- README.md
> add: fast-vite-electron

- README.md
> feat: add 3 template

- README.md
> add vite-material-ui

- README.md
> add Apps/Websites Context Note

- README.md
Replace [@vitejs/plugin-react-refresh](https://github.com/vitejs/vite/tree/main/packages/plugin-react-refresh) with [@vitejs/plugin-react](https://github.com/vitejs/vite/tree/main/packages/plugin-react)
> Replace @vitejs/plugin-react-refresh with @vitejs/plugin-react

- README.md
> add vite-plugin-global-style

- scripts/cleanup.mjs
> 🌈 style: const is more appropriate

- README.md
> add: stravital

- README.md
> add: vitailse

- README.md
> add: vitespa

- README.md
Add a Vite template.
https://github.com/TeXmeijin/vite-react-ts-tailwind-firebase-starter
Unlike the previous templates, this one uses Firebase v9, and React Router is already configured to support faster prototyping with Vite.
> add: vite-react-ts-tailwind-firebase-starter

- README.md
> add svelte kit to list

- README.md
<p align="center">
<a href="https://iles-docs.netlify.app">
</a>
</p>
> Add îles - islands of interactivity with Vue 3

- README.md
> add vite-plugin-require-transform

- README.md
> add vite-esbuild-typescript-checker TypeScript checker

- README.md
- [ x ] Title as described.
- [ x ] Make sure you put things in the right category.
- [ x ] The description of your item should be a sentence with less than 24 words.
- [ x ] Avoid using links and parentheses in description. 
- [ x ] Omit unnecessary words already provided in the context (e.g. `for Vite`, `a Vite plugin`).
- [ x ] Use proper case for terms (e.g. `GitHub`, `TypeScript`, `ESLint`, etc.)
- [ x ] When mentioning tools, omit versions whenever possible (e.g. use `TypeScript` instead of `TypeScript 4.x`, but keep `Vue 2` and `Vue 3` as they're incompatible).
- [ x ] When mentioning package names, use quotes whenever possible.
- [ x ] Always add your items to the end of …
> docs(templates): add vite-react-electron

- README.md
The template no longer has Windi CSS and Visualizer after the following commit 
https://github.com/0x219/vite-template-react-plus/commit/84661dd567c92b92dcf79ea360cd0a8d923301d7
> Remove Windi CSS and Visualizer from vite-template-react-plus description

- README.md
> docs: add  vite-plugin-simple-gql

- README.md
It generate a self contained and gziped file `index.html.gz`。Use for small space drive and embedded device. Alike ESP32 OTA mode just less than 170KB space!
> add starter template for embedded device

- README.md
> docs: add vite-plugins-vue2-svg

- README.md
vue-tail-fire is a public template powered by latest and greatest technologies like Vite, Vue 3, Firebase 9, Tailwind CSS.
> docs: add vue-tail-fire

- README.md
> docs: add vuelix

- README.md
I didn't add the items to the end of lists because I thought that `@vitejs` plugins should be listed first as they're more official. I can update if desired
> List vite-plugin-svelte, @vitejs/plugin-legacy, and @vitejs/plugin-vue-jsx

- README.md
> Added vite-react-vendor-split template

- README.md
> docs: add vite-vue2-mpa-template

- README.md
> docs: add ssr framework which use vite

- README.md
> Add Stitches+Radix starter template

- README.md
> docs: add CRA migration guide

- README.md
> feat: add vite-quasar starter

- README.md
[@zougt/vite-plugin-theme-preprocessor](https://github.com/GitOfZGT/vite-plugin-theme-preprocessor) - Easily implementing dynamic themes based on LESS or SASS.
> > Please make sure all the requirements are satisfied, otherwise the PR could be closed without further notice.
> 
> ## Checklist
> * [x]  Title as described.
> * [x]  Make sure you put things in the right category.
> * [x]  The description of your item should be a sentence with less than 24 words.
> * [x]  Avoid using links and parentheses in description.
> * [x]  Omit unnecessary words already provided in the context (e.g. `for Vite`, `a Vite plugin`).
> * [x]  Use proper case for terms (e.g. `GitHub`, `TypeScript`, `ESLint`, etc.)
> * [x]  When mentioning tools, omit versions whenever possible (e.g. use `TypeScript` instead of …
> docs: add @zougt/vite-plugin-theme-preprocessor

- README.md
> docs: add vite-plugin-twig

- README.md
> docs: add vite-plugin-remove-console

- README.md
> docs: add vite-plugin-stache

- README.md
> feat: add plugin loader  vite-plugin-raw

- README.md
> docs: add vite-plugin-flow

- README.md
> docs: Add i18n/graphql dts gen intergration plugin

- README.md
> Add vite-vue2-ts-starter.

- README.md
> feat: vue3-mobile-template

- README.md
> docs: add vue3-template to Templates / Vue 3

- README.md
> docs: add Astro

- README.md
> add: vite-plugin-webfont-dl

- README.md
- [○] Title as described.
- [○] Make sure you put things in the right category.
- [○] The description of your item should be a sentence with less than 24 words.
- [○] Avoid using links and parentheses in description. 
- [○] Omit unnecessary words already provided in the context (e.g. `for Vite`, `a Vite plugin`).
- [○] Use proper case for terms (e.g. `GitHub`, `TypeScript`, `ESLint`, etc.)
- [○] When mentioning tools, omit versions whenever possible (e.g. use `TypeScript` instead of `TypeScript 4.x`, but keep `Vue 2` and `Vue 3` as they're incompatible).
- [○] When mentioning package names, use quotes whenever possible.
- [○] Always add your items to the end of a list.
- [○] The …
> add: vite-vue2-simple-starter

- README.md
> docs: add 'vite-plugin-dev-manifest' and 'vite-plugin-babel-dev'

- README.md
> docs: add vite-plugin-resolve

- README.md
> feat: add Modern Vue repo

- README.md
> doc: add  vite-react-ts-ghactions-template

- README.md
> docs(template): add electron-vite-boilerplate

- README.md
> docs(plugin): add vite-plugin-electron-renderer

- README.md
Add Vite implementation to WinterCMS ecosystem. It includes a theme and a plugin.
> Add WinterCMS to SSR implementations list

- README.md
> doc: add vite-plugin-watch-and-run

- README.md
> feat: add 11st-starter-kit to vanilla templates

- README.md
> Added link to CakePHP plugin

- README.md
> docs(plugins): add vite-plugin-fast-external

- README.md
> Added vite-plugin-nightwatch to Testing section

- README.md
> add: P5.js starter template

- README.md
> feat:add vite-compression-plugin

- README.md
> docs: add vite-plugin-dynamic-base

- README.md
> feat: Add vite plugin for pug template engine

- README.md
> docs: vite-vue3-typescript-webcomponent

- README.md
> docs: add vite-pinia-ts-windi-starter

- README.md
https://github.com/ebeloded/vite-plugin-redirect
> Add vite-plugin-redirect

- README.md
> feat: add chunk split plugin

- README.md
- [ x Make sure you put things in the right category.
> add: wordpress-vite-assets

- README.md
> docs: add vue3-ts-vite-vitest-todo

- README.md
> add: vite-plugin-image-presets

- README.md
> Add vite-react-ts-extended

- README.md
> add: vite-plugin-static-copy

- README.md
> add: for vitawind

- README.md
> feat: add ` vitectron` template

- README.md
> feat: add vite-plugin-live-reload

- README.md
> feat: add @import-meta-env/unplugin

- README.md
> docs: add vue3-tailwind3-website-starter

- README.md
> feat: add vite-plugin-simple-vconsole

- README.md
> docs: add vite-plugin-file-mock

- README.md
> feat: add vue starter template

- README.md
I've finally split out our angular vite plugin for NX and made it into a standalone package.
- [] The documentation is in English.
> Add Angular integration

- README.md
> docs: add vite-plugin-optimizer

- README.md
> docs: add Hathora

- README.md
> docs: update vite-template-react-plus address and name

- README.md
> feat: add vite-plugin-vue-inspector

- README.md
This template includes the following:
Linters:
CSS Frameworks:
Testing:
For more information: [repo](https://github.com/fabgrel10/vite-react-starter)
> Add React template with CSS frameworks and testing libraries

- README.md
> docs: add Vue Naive Admin

- README.md
> docs: add vite-plugin-esmodule

- README.md
> dosc: add vite-plugin-load-css-module

- README.md
> docs: add vue-admin-box

- README.md
> docs: add vite-plugin-remain-exports

- README.md
> feat: vivu-npm

- README.md
> feat: add vite-plugin-import-rewriter

- README.md
> feat: add Preview.js

- README.md
> feat: add vite-plugin-iso-import

- README.md
> feat: add vite-plugin-qrcode

- README.md
> docs: add Electron plugins section

- README.md
Update migration project address
> docs: update migration project address

- README.md
> Issue #415: vite-go backend integration for Go

- README.md
> docs: add chrome-extension-boilerplate-react-vite

- README.md
- [ x Always add your items to the end of a list.
> docs: update react related plugin and project

- README.md
> docs: add chrome-ext-template-preact-windi-vite

- README.md
Hello! I'm Ryota Murakami.  
I added new type of react template that is [RTK Query](https://redux-toolkit.js.org/rtk-query/overview).  
RTK Query is Redux official data fetching library that has perfect integration to [Redux Toolkit](https://redux-toolkit.js.org/).  
I hope this will be useful to try RTK Query instantly, Thank you!
> react: add vite-rtk-query template

- README.md
> docs: add vite-plugin-dynamic-import-module

- README.md
> add vite-react-proste

- README.md
> feat: add React-PWA v2

- README.md
> docs: add vite-plugin-mp

- README.md
> feat: add vite-plugin-xml-loader plugin

- README.md
> feat: add vue-pc-template

- README.md
> feat: add vite-react-ts-minimal-template

- README.md
> feat: add ViTauri template

- README.md
> docs: add vue-hbs-admin

- README.md
> docs: add vite-vue-proste

- README.md
> docs: add vue-vite-ssr

- README.md
> feat: add vite-plugin-babel-compiler

- README.md
> docs: add vite-vanilla-ts-lib-starter

- README.md
> feat: add vite-plugin-copy-files

- README.md
> docs: add react-vite-ssr

- README.md
`import.meta.glob` based lightweight routes Generater.
> feat: add vue3 router tool

- README.md
> Add New React Templates - Viact

- README.md
> docs: migrate repository

- README.md
> docs: add vite-plugin-commonjs

- README.md
> Add create-rust-app to "Backend Integrations" section

- README.md
> docs: add `vite-plugin-unocss-to-uni`

- README.md
> docs: add create-electron-vite

- README.md
> Add @modyfi/vite-plugin-yaml

- README.md
> docs: add vite-plugin-electron-quick-start

- README.md
> feat: add vite-plugin-progress

- README.md
> Add vavite to SSR libraries

- README.md
> feat: vite-plugin-vuedoc renamed

- README.md
> docs: add vite-plugin-head

- README.md
> docs: add vite-plugin-cem

- README.md
> docs(templates): add vue3-vant-mobile

- README.md
> docs: add vitest & vitest-mock-extended

- README.md
> add vite-vue2-ts-template-starter

- README.md
Adds vite-elm-spa to the Elm templates.
> Add vite-elm-spa to the list of Elm templates

- README.md
> 📃 docs: add OctoberCMS integration

- README.md
To improve to https://github.com/vitejs/awesome-vite/pull/482
> docs: add vite-plugin-electron-renderer

- README.md
A react component lib, and its demo site is built with vite and vite-plugin-react-pages and deployed on github-pages.
> docs: add App react-keyboard-navigator

- README.md
> docs(plugins): add vite-plugin-tencent-oss

- README.md
> docs: add Ladle into open source projects

- README.md
resolve: https://github.com/vitejs/awesome-vite/issues/492
> docs(templates): add "vite-petite-vue-starter"

- README.md
This repository seems to have been abandoned. Remove the link to it.
Fixes #496
> remove `create-vite-pwa`

- README.md
> docs: add vue3-powerbuild

- README.md
> docs: add vite-plugin-html-env

- README.md
> Add ViteRC to React Vite Templates

- README.md
> feat: add vite-plugin-importus plugin

- README.md
> add link to Symfony integration

- README.md
> **Note**: In draft as the repository is not 30 days old yet.
This plugin configures Vite for use with a Laravel Livewire, allowing components to be hot reloaded without losing their state when their blade or class files change.
- [Demo](https://twitter.com/FabioIvona/status/1543180409382604802) 
- [Laravel Livewire](https://laravel-livewire.com/)
Plugin authored by @fabio-ivona
> Add Laravel Livewire plugin

- README.md
> Add vite-plugin-inject-preload

- README.md
**Unlike many others, this Tailwind CSS starter template doesn't include or depend on any JS code. It's just pure HTML/CSS project starter.**
> docs: add vite-tailwind-starter

- README.md
> Add vite-plugin-shopify

- README.md
> docs: add vrttv-boilerplate

- README.md
> docs: add vue-ts-starter

- README.md
> docs: add CodeIgniter Vite

- README.md
> docs: add vite-plugin-browser-sync

- README.md
> feat: add jspm (vite-plugin-jspm) integration

- README.md
[React Starter Kit](https://github.com/kriasoft/react-starter-kit) (★21k) - React, React Router, Material UI, Firebase Auth, TypeScript, ESLint, Prettier, Jest.
> docs: Add React Stater Kit template

- README.md
> feat: 🎸 add vite-plugin-build

- README.md
> readme: change `them` to `dependencies`

- README.md
> add new project to Vue 3 templates

- README.md
> Add vite-mern-template

- README.md
> doc: update `vite-react-ts-ghactions-template` description

- README.md
> Add express and mongoose in the description

- README.md
> docs: add new Vue 2 project vitify-admin

- README.md
> docs: update plugin info

- README.md
> docs: add vite-plugin-print-urls

- README.md
> docs: add vite  starter projects with cli

- README.md
> added maifeeulasad/react-pipeline

- README.md
> Add React template - Varsarr 

- README.md
> viterjs-template added

- README.md
> docs: add vite-plugin-browserslist-useragent

- README.md
> add react-vite-ts-boilerplate link

- README.md
> Add Flask-Vite

- README.md
> feat: add plugins vite-plugin-env-switch vite-plugin-msg-log

- README.md
> docs: add vite-react-universal template

- README.md
> docs: add vite-plugin-document

- README.md
Hello !
The only requirement that is not met is that the repo must exist for more than 30 days. However I really think that this plugin could interest a lot of people and be useful ( At least I hope so ! ) that's why I'm doing this PR.
If ever it's an essential requirement, don't worry, don't hesitate to close the PR and I'll do it again next month 👍 
https://github.com/Julien-R44/vite-plugin-validate-env
> docs: add `vite-plugin-validate-env`

- README.md
> docs: vite-plugin-zip-pack added

- README.md
> feat: add island.js

- README.md
> docs: Add plugin vite-plugin-virtual-mpa

- README.md
This repo is a fully-featured scaffold using the following:
- Vite (3.x)
- Vitest
- Pinia
- NaiveUI
- Vue Router
- Vue 3
- Tailwind CSS
- Cypress E2E
- GitHub Workflows testing Cross OS compatibility
- Existing and functional Unit/E2E tests with near 100% global coverage
> Add vue-vite-tw-ts Repo to Vue 3 Scaffolds

- README.md
> Adding Deluze/electron-vue-template to the Electron section

- README.md
> docs: added vituum family plugins for vite

- README.md
> docs: add vitron to list

- README.md
> feat: add vite-vue-box

- README.md
> docs: add tailwindcss-vite-plugin

- README.md
This repo had been deleted, Page Not Found
> docs: vite-plugin-fast-external had been deleted

- README.md
> docs: add vite-vue2-js-starter-template to list

- README.md
**Renamed `kometolabs/vite-tailwind-starter` to [kometolabs/vite-tailwind-nojs-starter](https://github.com/kometolabs/vite-tailwind-nojs-starter) to better highlight its unique feature.**
> fix: Renamed kometolabs/vite-tailwind-starter to vite-tailwind-nojs-starter

- README.md
> docs: add conditional-compile and patch-env plugin

- README.md
> add plugin vite-plugin-setting-css-module

- README.md
> docs: add vite-vue-js-starter-template to list

- README.md
> docs: add vutron to list

- README.md
> docs: add cypress-vite to list

- README.md
Add starter template:
Vue 3 + TypeScript + Vite + Bootstrap Vue 3 + Vitest + ESLint + Prettier + Husky
> docs: add vue3 + bootstrap-vue-3 to list

- README.md
> docs: add vite-plugin-debug to list

- README.md
> docs: add unplugin-compression

- README.md
> docs: add vite-plugin-version-mark

- README.md
> docs: vite-plugin-react-inspector added

- README.md
> feat: add vite-plugin-assemblyscript-asc

- README.md
> docs: add vite-solid template

- README.md
- Documentation website: https://www.vitest-preview.com
- Launch announcement: https://twitter.com/hung_dev/status/1584491260773289984
- GitHub: https://github.com/nvh95/vitest-preview
- Twitter account: https://twitter.com/VitestPreview
> 🖼 docs: add vitest-preview

- README.md
- [] The plugin uses Vite-specific hooks and can't be implemented as a [Compatible Rollup Plugin](https://vitejs.dev/guide/api-plugin.html#rollup-plugin-compatibility).
> docs: unplugin-svg-component

- README.md
> docs: add vite-plugin-externals-extension

- README.md
> docs: add vite-plugin-css-export

- README.md
Since this is a new section, I wasn't exactly sure where to put it so I just put it after React given our similarity to them.
> Add preset from Preact team to framework list

- README.md
> docs: add vite-electron-plugin

- README.md
Add starter template: Vite + Tailwindcss
> docs: add vite + tailwindcss to list

- README.md
> fix: Add new Vue I18n integration plugin

- README.md
> docs: add react-vite-template

- README.md
This PR adds [Nx](https://nx.dev/) in two sections:
1. Getting Started: Our react preset initialized the workspace with Vite and Vitest
2. Migration: The `npx nx init`command migrates a CRA project to Nx + Vite + Vitest
> docs: add Nx scaffolding and migration links

- README.md
> docs: add vite-plugin-optimize-css-modules

- README.md
add vite plugin: vite-plugin-mock-dev-server
> docs: add vite-plugin-mock-dev-server

- README.md
> docs: add vitesse-solid and vite-plugin-solid-markdown

- README.md
> + vite-plugin-api as Helpers

- README.md
> chore(readme): adds ultimate vue3/vite/ts template to readme file

- README.md
> docs: add react-xs-admin

- README.md
> add: Laravel official plugin

- README.md
> docs: add template: vulcan

- README.md
> feat(docs): add unplugin-imagemin

- README.md
> add vite-plugin-qiniu-oss

- README.md
> docs: add vite-plugin-remark-rehype

- README.md
> docs: add vite-plugin-entry-shaking

- README.md
> docs: add vite-plugin-stylelint

- README.md
> docs: add vite-vue-h5-app template

- README.md
> docs: add vite-plugin-image-optimizer

- README.md
> Add template vite-mui-ts

- README.md
> docs: vue3-ts-compositionAPI-i18n-fetchData

- README.md
> docs: add vite-plugin-graphiql

- README.md
> add Compiiile open-source project

- README.md
> docs: add vite-plugin-graphql-server

- README.md
> docs: add leo-react-app

- README.md
> docs: add vite-plugin-auto-alias

- README.md
> Added Haxe plugin

- README.md
> docs: add vite-plugin-shortcuts

- README.md
> docs: add vite-express

- .github/pull_request_template.md
Correct typos in the PR template
> docs(pr template): correct typos

- README.md
> docs: add dockerized vite tailwindcss handlebars

- README.md
> docs: updating my template to React 18

- README.md
> Added template-vite-react-ts-tailwind

- README.md
> add vite-plugin-image-placeholder

- README.md
> docs: add vite-plugin-multiple

- README.md
> docs: add vite-plugin-isomorphic-import

- README.md
> docs: add vite-phaser-ts template

- README.md
> [Rename] Project name rename

- README.md
> docs: add vite-plugin-doubleshot

- README.md
> docs: add vite-plugin-target

- README.md
- Add react with tailwindcss + tests
- Update README.md
- Add vite-plugin-restart and vite-plugin-full-reload to Helpers section
- docs: Add vite-plugin-stimulus-hmr
- add plugin 'vite-plugin-tips'
- Update README.md
- Update README.md
- docs: add vite-remark-html
- Update README.md
- feat: add 2 vitesse template
- feat: add cleanup script
- chore: fix lint
- fix: remove out-dated links
- Add @nabla/vite-plugin-eslint
- add vite-plugin-commonjs
- Fix an lint error on Line 162
- feat: add vue2/3 todo action template
- Move Django item into its own category
- Add Vue SSR templates
- Alphabetize section "Integration with Backends"
- docs: added a plugin vite-plugin-external
- docs: add vite-plugin-react-refresh
- add(integrations): Laravel Vite
- feat: Added vite-reactts17-chakra-jest-husky …
> Update template description

- README.md
> feat: add vite-plugin-vue-preview

- README.md
> feat: add vite-plugin-vue-sfc-in-js

- README.md
> add vite-plugin-importmap

- README.md
This project provides a basic dev setup intended for `Single Page Application` (SPA) development. It contains already configured tools and libraries providing a quick and seamless start, making the Developer Experience (DX) and scalability of your project easily manageable. It also shows a practical application of selected tools and practices in a form of a demo app.
Bearing in mind flexibility and openness to various tools and preferences, this template allows you to adjust your workflow to your needs, assuring best practices and following opinionated frontend/React trends at the same time.
Thus, the template provides two different versions, differing in complexity and spectrum of solved problems.
The most basic config of the dev environment. It provides seamless DX and assures a legible …
> docs: add vite-react-ts template

- README.md
add vite-plugin-style-vw-loader
> 📃 docs:add vite-plugin-style-vw-loader

- README.md
> docs: add vite-plugin-find-image-duplicates

- README.md
> doc: add vite-plugin-clean

- README.md
> docs(plugins): add add vite-plugin-gitlab-flow

- README.md
> Added S3 Plugin

- README.md
> feat: add unplugin-fonts

- README.md
> Add SSR framework Vise

- README.md
> docs: add vite-plugin-vitepress-auto-sidebar

- README.md
> docs: add unplugin-config

- README.md
> docs: add vue3 vant pinia ts demo

- README.md
> docs: add vite-plugin-svg-spritemap

- README.md
> docs: add vitesse-lite-solid

- README.md
> docs: add vite-plugin-vue-css-modules

- README.md
Adds up-to-date template with React, Javascript, TailwindCSS, ESlint, Prettier, Pre-commit.
I'm submitting this PR as most of other templates are using Typescript or they don't have TailwindCSS.
> docs: add react-vite-tailwindcss-template

- README.md
I fixed the links and added some missing official plugins.
closes #719
> docs: update official plugins

- README.md
> docs: add vite-asset-collector for TYPO3

- README.md
> docs: add vite-plugin-vue-nested-sfc

- README.md
Define constants for your project to facilitate reuse of your code across multiple products
- [ x] Title as described.
- [ x] Make sure you put things in the right category.
- [ x] The description of your item should be a sentence with less than 24 words.
- [ x] Avoid using links and parentheses in description. 
- [ x] Omit unnecessary words already provided in the context (e.g. `for Vite`, `a Vite plugin`).
- [ x] Use proper case for terms (e.g. `GitHub`, `TypeScript`, `ESLint`, etc.)
- [ x] When mentioning tools, omit versions whenever possible (e.g. use `TypeScript` instead of `TypeScript 4.x`, but keep `Vue 2` and `Vue 3` as they're incompatible).
- [ x] When mentioning …
> docs: add vite-plugin-global-const

- README.md
> feat: add antdv-pro

- README.md
> Add Vite templates for TinyBase

- README.md
> add vue-ssr

- README.md
> Add unplugin-vue-router

- README.md
===========================
Update my project name and libraries to the latest.
> [react] rename vite-react-ts-extended to create-react-app-vite

- README.md
> Add vite-plugin-thumbhash

- README.md
> feat: add vite-plugin-vue-devtools

- README.md
> docs: add vite-plugin-auto-mpa-html

- README.md
> docs: add vite-plugin-react-mpa

- README.md
> docs: add `vite-plugin-turbo-console`

- README.md
> docs: adds fastify-dx

- README.md
> Added template-vite-svelte-ts-tailwind

- README.md
> feat: add vite-plugin-cloudflare-functions

- README.md
> docs: add vite-plugin-cli-copy

- README.md
> chore: add vite-plugin-i18n-autoimport

- README.md
> docs: add description

- README.md
> add plugin for @dvgis/dc-sdk

- README.md
> Add Vite.AspNetCore

- README.md
> add vite-plugin-copy-dts  and  vite-run

- README.md
> feat: add vite-ssr-boost library and vite-ssr-boost-template

- README.md
> docs: add vite-react-ssg

- README.md
> docs: add unplugin-vue-images

- README.md
> docs: add unplugin-zip-pack

- README.md
> docs: add vite-plugin-module-list

- README.md
> docs: add vite-plugin-html-injection

- README.md
I have 2 questions.
The project in itself is not a commercial product but facilitates the use of it. So can this be added on this list?
Does this require a new `Deployment` category?
> Add vite-plugin-vercel

- README.md
> feat: add antd-vue3-admin

- README.md
> Vite plugin remix

- README.md
> Add `vite-plugin-node-polyfills`

- README.md
> docs: add `vite-plugin-cdn2`

- README.md
> docs: add `vite-plugin-doctest`

- README.md
> docs: add vite-react-ts-shadcn-starter

- README.md
> docs: add create-awesome-node-app

- README.md
plugin-dynamic-proxy
- [x ] Avoid using links and parentheses in description.
> add plugin-dynamic-proxy

- README.md
> docs: add unplugin-info

- README.md
> Add `vite-plugin-typescript-transform`

- README.md
> docs: add vite-react-chakra-starter and vite-react-tailwind-starter

- README.md
We provided a link to a template repository pre-configured to support features like server-side rendering, static page generation, single-page application hosting, and API provision.
> docs: add monorepo template

- README.md
> Add vite-react-dapp-template

- README.md
> Add template for domco SSG

- README.md
> Add VanJS JS & TS Templates

- README.md
> adding vite-express-ssr-ts template

- README.md
> Add vue file upload management system

- README.md
> Add vite-plugin-auto-origin

- README.md
> add vite-plugin-kit-routes

- README.md
> add plugin vite-plugin-markdown-mermaid

- README.md
> add React Flow and Svelte Flow templates

- README.md
> Add vite-plugin-deadfile

- README.md
> Added vite-bundle-analyzer to README.md

- README.md
> Add Viject

- README.md
> Added vite-font-extractor-plugin to README.md

- README.md
> add vite-plugin-i18n-detector

- README.md
- [x ] Make sure you put things in the right category.
> add template for frontends based on react and vitejs

- README.md
Removes `vite-plugin-react-refresh` as it doesn't exist anymore.
> docs: remove vite-plugin-react-refresh

- README.md
> Added vite-plugin-ngrok

- README.md
> feat: add vite-plugin-legacy-swc

- README.md
> feat: add react-gravity-ui-template

- README.md
> feat: add kima (wordpress starter template)

- README.md
> feat: add vite-plugin-lqip

- README.md
> +vite-plugin-rest-api

- README.md
> + Rename vite-plugin-api-routes

- README.md
> docs: add arco-admin to Vue 3 list

- README.md
> add plugin `vite-plugin-ms-clarity`

- README.md
> add vite-template-awesome-soho in React

- README.md
> feat: add `vite-vanilla-library-template`

- README.md
> feat: add @cyco130/vite-plugin-mdx

- README.md
> docs: Add @laynezh/vite-plugin-lib-assets to Transformers List

- README.md
> feat: add vite-manifest-parser

- README.md
> feat: add vite-awesome-svg-loader

- README.md
> Update README.md: Add SSRx and Vike

- README.md
> docs: remove vite-tailwind template, link returning 404

- README.md
add vite-plugin-bundle-prefetch
> add vite-plugin-bundle-prefetch

- README.md
- [ x Omit unnecessary words already provided in the context (e.g. `for Vite`, `a Vite plugin`).
> Added Materio Free Vuetify NuxtJS Admin Template

- README.md
> Added `@vheemstra/vite-plugin-imagemin`

- README.md
> Add vite-plugin-lib-types

- README.md
> feat: add vite-plugin-react-rich-svg

- README.md
> feat: add css-media-splitter

- README.md
> Add vite-plugin-oxlint

- README.md
> Add vite-plugin-minipic

- .gitignore
- README.md
> Add @tomjs/vite-plugin-electron

- README.md
> Vite alpine template with running example in GitHub Pages

- README.md
> Add vite-plugin-twig-drupal and Drupal backend integration links

- README.md
> Add @tomjs/vite-plugin-vscode

- README.md
> Add @tomjs/vite-plugin-html and @tomjs/vite-plugin-iconify

- README.md
> Add ReTail

- README.md
> chore: add github-action-template

- README.md
It's not immediately obvious that Vinxi can be used to get SSR with Vite, so included it in the description, and made the link go directly to the SSR page.
> Update README.md: Add Vinxi to SSR section

- README.md
> add vite-plugin-robots

- README.md
> docs: add vite-react-redux-saga-typescript template

- README.md
> feat: added vite-plugin-vitepress-auto-nav

- README.md
> add vite-plugin-px-rem-vw

- README.md
> Add `vite-complete-react-app`

- README.md
> add `vite-plugin-vue-style-bundler` for vue3

- README.md
> Update import-meta-env link

- README.md
> chore: update the vue3-vant-mobile reference

- README.md
> Add plugin `@stylin/vite-plugin`

- README.md
> A simple plug-in for configuring multi-page applications
> docs: add vite-plugin-mpg

- README.md
> docs: add vue3 template

- README.md
> Add vite-plugin-pretty-module-classnames

- README.md
> docs: Update broken link + added new Vite plugin to the list

- README.md
> fix: synchronised update of the latest links

- README.md
> Add react tanning template

- README.md
> add PHP-Vite

- README.md
> docs: add dataviz-explorer app

- README.md
> Add vite-plugin-serve-static

- README.md
> 📃 docs: add vite-plugin-style-vw-loader

- README.md
> Add vite-plugin-dir2json

- README.md
I was edit description for contain the latest features :)
> Update chrome-extension-boilerplate-react-vite README description

- README.md
- Added a Neutralino category with a short description about Neutralino
- Add a template for vite-react-neutralino-template in the Neutralino category
> Add a template for vite-react-neutralino-template + a Neutralino category

- README.md
> Feature: `vite-plugin-pagefind`

- README.md
Powered by Vite (SSR/Browser) and Lit SSR
> Add Gracile full-stack meta-framework

- README.md
> Adds minor changes to the description of vite-plugin-pretty-module-classnames

- README.md
> add vite-plugin-abbrlink

- README.md
> Add WXT to "Projects Using Vite.js"

- README.md
> The plugin does not use Vite-specific hooks and can be implemented as a [Compatible Rollup Plugin], but has no purpose without `Vitest`, hence `Vite`.
> Add vite-plugin-vitest-cache

- README.md
> docs(templates): add rvtgb starter template

- README.md
> docs: add vite-plugin-native

- README.md
This commit adds a link to a backend integration for Go. I still consider it beta, but it comes with an example to illustrate usage.
> Add backend integration for Go

- README.md
> feat: vite-vlugin-vercel-skew-protection

- README.md
> docs: add vite-biome-tailwind-template

- README.md
> Add `vite-ts-lib-starter` to starter templates

- README.md
> feat: add @mistjs/vite-plugin-px2viewport

- README.md
> Add poyro to list

- README.md
> Add vite plugin for TYPO3 to list

- README.md
WordPlate is a WordPress-based platform that provides sensible defaults and utilizes Vite.js for frontend development. It demonstrates how to seamlessly integrate Vite.js with WordPress using new methods, such as the `wp_enqueue_script_module` function.
- [`vite.config.js`](https://github.com/vinkla/wordplate/blob/master/vite.config.js)
- [`functions.php`](https://github.com/vinkla/wordplate/blob/c7009dffd849661c9b96e3334087dcf7863a157d/public/themes/wordplate/functions.php#L18-L33)
WordPlate receives significant traffic [from this Reddit thread](https://www.reddit.com/r/Wordpress/comments/y9fe2j/comment/jgs95if/), where people try to find out how to integrate Vite.js with WordPress.
> Added WordPlate link under WordPress

- README.md
> add react dapp starter template

- README.md
> Add CSP Guard to list

- README.md
> docs: add vue3 i18n vite-ts-starter

- README.md
> feat: add vite-plugin-bundle-obfuscator

- README.md
This PR adds template with React, TypeScript and Jest.
[Live DEMO](https://codesandbox.io/p/github/ivanzusko/vite-template-react-ts-jest/main)
> Add `vite-template-react-ts-jest`

- README.md
> Add the vite-plugin-dynamic-chunk plugin to the Bundling section.

- README.md
Vite template repo that can be deployed and hosted with AWS Amplify Hosting with minimal effort. It includes Vite SSR + Express APIs and uses react, ts, tailwind, and virtual react router. Check it out if you're looking for a quick way to scaffold a full-stack Vite project hosted on AWS infra.
* Repo: https://github.com/bebeal/vite-amplify
* ~4 mins from fork-to-finish for a successful deployment: https://www.youtube.com/watch?v=dsHQUgwkZ7s
* Demo Site: https://www.vite-amplify.com/
> Add vite-amplify template

- README.md
> chore: add vite-plugin-envtype-patch

- README.md
> feat: add `vite-plugin-remix-flat-routes`

- README.md
> add @yuanjianming/unplugin-image-convert

- README.md
https://github.com/bavragor/vite-svelte-docker-template
> add tony-stark-eth/vite-svelte-docker-template

- README.md
> feat: add react boilerplate template

- README.md
> docs: add Revili to Open Source

- README.md
> docs: add vite-plugin-eslint2

- README.md
> docs: add @yuanjianming/unplugin-compress-svga , @yuanjianming/unplugin-font-spider

- README.md
- [ x Use proper case for terms (e.g. `GitHub`, `TypeScript`, `ESLint`, etc.)
> docs: add genaicode/vite-plugin

- README.md
> Add vite-plugin-year

- README.md
> docs: add vite-plugin-replace-lodash

- README.md
> docs: add HuLa

- README.md
> Add new react template

- README.md
> add vite-plugin-llms for llms.txt specification support

- README.md
> Bundling Add vite-plugin-singlefile-compression

- README.md
>  Add "vite-rs" to "Backend Integrations" section

- README.md
> add vite-plugin-dynamic-prefetch

- README.md
Added official phaser vite templates
> add official phaser + vite templates

- README.md
> add vite-plugin-csp

- README.md
> docs: add vite-ts-bulma-sass-template

- README.md
> + vite-plugin-ssr-config

- README.md
> + vite-plugin-builder

- README.md
> docs: add portfolio template usign vite-react with Manifest

- README.md
Add starter template with Vue 3 + Vite + Tailwind CSS 4 + DaisyUI 5 + Sass
> Add vite-vue3-tailwind4-daisyui5-starter-template

- README.md
> add `vite-plugin-vue-style-in-template`
