- README.md
> chore: add rollup plugins section

- README.md
add new template.
- [vite-electron-quick](https://github.com/MangoTsing/vite-electron-quick) - Starter template with Vue 3, TypeScript and Electron 11.x.
> feat: add vite-electron-quick template

- README.md
@antfu I placed the link under rollup plugins, but I do not know if that is the correct place for it.
Also added a few more compatible plugins to the list (the image one needs enforce pre, added a note about that too).
I was thinking about the plugins listed as covered in https://vite-rollup-plugins.patak.dev. IMO including all the plugins here may occupy too much space in the …
> chore: vite rollup plugins compatibility list

- README.md
@antfu I can merge this PR, but wanted to ask your opinion about including the **Covered by default in Vite** section. 
If we do not include them, I think we are giving the impression that these plugins are not compatible. But including them as is could be a bit confusing also, because users needs to dig in the Vite docs to understand how they are actually covered. In [Vite …
> feat: official rollup plugins compat update

- README.md
Add ressource https://github.com/brillout/vite-plugin-mdx.
> Add @brillout/vite-plugin-mdx

- .github/pull_request_template.md
@antfu add a step in the Plugin/Tools checklist about following the [Vite Plugin Conventions](https://vitejs.dev/guide/api-plugin.html#conventions). In case other conventions are added in the future, I think it is better to just point to that section to avoid the need to keep the template in sync. If you would prefer a different wording, or explicitly naming the conventions, please go ahead 👍🏼
> chore: plugin conventions in PR template

- README.md
Rendered version: https://github.com/brillout/awesome-vite/tree/refactor-ssr#ssr.
Follow up of https://discord.com/channels/804011606160703521/804061937029218334/844266963244941348.
The plan is to add a link to the SSR section at https://vitejs.dev/guide/ssr.
@frandiox How about we change the description of `vite-ssr`? Maybe `SSR with bring your own router`?
cc @patak-js
> docs: refactor ssr

- README.md
[Vite.js](https://vitejs.dev/) & [Rollup](https://rollupjs.org/) plugin for generating critical CSS that uses the [critical](https://github.com/addyosmani/critical) generator under the hood.
> Add rollup-plugin-critical

- README.md
Add app and website `react-device-frameset` which is built by `Vite`, and its demo site is powered by `vite-plugin-react-pages`.
> Add app and website react-device-frameset

- README.md
The `vite-plugin-ssr` introduction & docs now live at https://vite-plugin-ssr.com/.
> docs: update vite-plugin-ssr link

- README.md
There is two missing points on the `Vite Plugins Conventions`:
- Add `vite-plugin` keyword. I will publish a minor version to add it if it's only thing blocking
- A reason why it's not a rollup plugin: Is keeping the possibility to use future vite only API's and never tested the project outside of Vite a valid reason?
> Add @nabla/vite-plugin-eslint

- README.md
The plugin `vite-plugin-externals` could not exclude externals of pre-bundling dependencies, then I found a new way to solve this problem.
> docs: added a plugin vite-plugin-external

- README.md
> add vite-plugin-vue2-suffix plugin

- README.md
> Add `vite-plugin-tauri`

- README.md
> Add: vite-vue3-tsx-starter

- README.md
> add vite-plugin-content

- README.md
> docs: add vite-plugin-federation

- README.md
> feat: add vite-plugin-require

- README.md
> feat: add vite-plugin-wasm-pack

- README.md
> feat: add vite-plugin-css-modules

- README.md
> add vite-plugin-macro

- README.md
> add vite-plugin-comlink

- README.md
Adds the Vitalis model to the list of models for vue 3.
vitalis is a complete template that has Vue 3 - Vue Router 4 -
TypeScript - Tailwind CSS - ESlint - Prettier and a few more plugins for
Tailwind.
> Add Vitalis template for vue 3

- README.md
> docs: add Vitecamp template for Vue3

- README.md
At present, all `Electron` templates are mixed in different categories.  
This "PR" classifies them into the `Electron` category. 🎯
> chore: move all electron-template to `Electron` category

- README.md
Adds vite-tailwind-stimulus-starter to the _vanilla templates_ section, since Stimulus is much closer to vanilla js than it is to larger and more popular front-end frameworks. Could also be in a new section of its own or in the _other_ section. Looking for input on this. Thanks!
---
> Add vite-tailwind-stimulus-starter

- README.md
- [vite-plugin-gltf](https://github.com/nytimes/rd-bundler-3d-plugins) - Load, transform, optimize, and compress glTF 3D files.
- Tested with Vite 3.x+, not Vite 2.x.
- We publish both vite- and rollup-prefixed plugins. They currently contain the same code, but I found it very [difficult](https://github.com/vitejs/vite/discussions/7515) to get the Rollup-compatible implementation working in Vite, and want to reserve the option of branching the implementations later.
> docs: add vite-plugin-gltf

- README.md
This PR adds a starter template for using Knockout.js with Vite and TypeScript.
Sure thing, if you are toying with the idea of using Vite, you're probably also using a modern frontend framework like React, Vue, Svelte... . And Knockout is anything but modern. **But:** I know there are still many legacy projects using Knockout (I mean, look at the weekly downloads at NPM). And perhaps these projects don't want to port the whole application to a new framework but still use a more modern bundler like Vite.
> docs: add vite-vanilla-ts-knockout template

- README.md
This PR adds a starter template for React with TypeScript and Tailwind CSS, using Vite.
This template is configured with tools (along with Vite) to enhance the development experience when working on a React application.
1. ESLint + Prettier → enforce code styles and format the code
2. Vitest → write specs for the application
3. Husky → ensures that the build is green, i.e. all of the specs pass, before making a commit
4. Tailwind + CSS Module → write scoped styles for your components with Tailwind's utility classes
Tailwind provides utility classes for patterns that are commonly repeated when writing CSS code. With the help of CSS modules, you can use these utility classes to create scoped styles while writing minimal CSS code.
> docs: add vite-react-ts-tailwind template

- README.md
- [`vite-plugin-solid-markdown`](https://github.com/xbmlz/vite-plugin-solid-markdown) was already listed, but miscategorized under the "framework-agnostic plugins" section
- [`vite-plugin-solid-svg`](https://github.com/jfgodoy/vite-plugin-solid-svg) is new ✨ 
Both added underneath the SolidJS plugins section.
---
> Add two Solid plugins

- README.md
The '@nxext/angular-vite' plugin link is broken because this plugin has moved to an experimental repo.
Fix https://github.com/vitejs/awesome-vite/issues/711
> docs: update @nxext/angular-vite link

- README.md
When I have publish and made this plugin, the plugin https://github.com/g-makarov/vite-plugin-svg-spritemap didn't exist yet. It is a problem to have two project with the same name (but not the same scope) ?
> docs: add @spiriit/vite-plugin-svg-spritemap

- README.md
> docs: add `vite-react_best_practices-template`

- README.md
> Added Vite Vanilla JavaScript Template to Readme

- README.md
closes https://github.com/vitejs/awesome-vite/issues/427
> add `@storybook/builder-vite` and `@builder.io/partytown`

- README.md
> chore: modify broken links

- README.md
> Vite plugin json server

- README.md
> docs: add generouted to react and solid routing

- README.md
vue3 template: vue3-quick-start, vite-plugin: vite-plugin-meta-env
> docs: add vue3-quick-start & vite-plugin-meta-env

- README.md
The [vite-plugin-inject-preload](https://github.com/Applelo/vite-plugin-inject-preload) will be deprecated soon and [unplugin-inject-preload](https://github.com/Applelo/unplugin-inject-preload) will replace it.
- [x ] Not a commercial product.
> replace vite-plugin-inject-preload by unplugin-inject-preload

- README.md
> docs: Add vite-plugin-singlefile.

- README.md
> Added RoyRao2333/template-tauri-vite-react-ts-tailwind

- README.md
> docs: add unplugin-auto-export

- README.md
> docs: add vite-plugin-console-line

- README.md
> add vite-plugin-public-typescript

- README.md
> docs: Modifying the technology stack.

- README.md
> + vite-plugin-docker

- README.md
[vite-react-component-library-starter](https://github.com/rayyamhk/vite-react-component-library-starter) is a starter template for creating React component libraries using Vite. It includes a robust set of features to help you develop, test, and build your library efficiently.
> Add new template "vite-react-component-library-starter"

- README.md
> vite & rollup plugin to remove jsx 'data-testid' attribute from production builds

- README.md
Removes vite-plugin-eslint which is _**majorly broken**_ and seemingly long abandoned- unmaintained with _no pull-requests merged or commits added in the last year_. (No notes from @gxmari007 in repo readme about project status ¯\\\_(ツ)_/¯ )
https://github.com/gxmari007/vite-plugin-eslint/issues/83
> Remove: vite-plugin-eslint

- README.md
This PR adds `php-vitelinker` under 'Integrations with Backends' section.
> add `php-vitelinker` under 'Integrations with Backends' section

- README.md
> docs: Add the @yoichiro/vite-plugin-handlebars plugin to the Transformers section

- README.md
add vite-plugin-magic-preloader
> add vite-plugin-magic-preloader

- README.md
https://github.com/wille/vite-preload
https://www.npmjs.com/package/vite-preload
No, vite-preload is also a runtime library and not just a plugin.
> Add vite-preload

- README.md
- [] The repo should be at least 30 days old.
> Add jrtderonde/vite-create-production-server-plugin

- README.md
> docs: Add vite-plugin-page-html

- README.md
> Add `vite-plugin-material-symbols`

- README.md
The old module federation repo have been stale for  months, and development have been picked up recently by the module-federation official repo.
Not sure if the old one should be removed, so added it to at the bottom for now.
> docs: add official maintained module federation vite plugin

- README.md
> add fable vite plugin

- README.md
> Add @responsive-image/vite-plugin to Loaders
